<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="footer-checkout">
    <img src='<?php echo $this->getViewFileUrl('images/logo-metasports.png'); ?>' title="" alt="" width="78" height="39">
</div>

<div class="copyright">
    <a href="https://www.lyracons.com">
        <img src='<?php echo $this->getViewFileUrl('images/logo-lyracons.png'); ?>' title="" alt="" width="100" height="20">
    </a>
</div>
