<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Cart $block */

/** @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();

/** @var $itemHelper \Lyracons\QtyIncrement\Helper\Data */
$itemHelper = $this->helper('Lyracons\QtyIncrement\Helper\Data');
?>
<?php foreach ($block->getChildNames() as $childName): ?>
    <?= /* @noEscape */ $block->getLayout()->renderElement($childName, false) ?>
<?php endforeach;?>
<div class="box-tocart">
    <fieldset class="fieldset">
    <?php if ($item->canHaveQty() && $product->isVisibleInSiteVisibility()): ?>
        <div class="field qty">
            <label class="label" for="qty[<?= $block->escapeHtmlAttr($item->getId()) ?>]"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
            <div class="control qty">
                <span class="minus">
                    <button
                            type="button"
                            title="<?= __('Reduce the quantity'); ?>"
                            class="sub-cart"
                            data-cart-item-id="<?php /* @escapeNotVerified */
                            echo $item->getId() ?>"
                            data-cart-item-increment="<?php echo $itemHelper->getQtyIncrementsByProduct($product); ?>"
                            data-role="sub-cart"
                    >-</button>
                </span>
                <?php $value = (($block->getAddToCartQty($item) * 1) > $itemHelper->getQtyIncrementsByProduct($product)) ?
                                   ($block->getAddToCartQty($item) * 1)
                                   : $itemHelper->getQtyIncrementsByProduct($product); ?>
                <input type="number" 
                data-role="qty" 
                id="qty[<?= $block->escapeHtmlAttr($item->getId()) ?>]" 
                class="input-text qty qty-not-visible-<?= $block->escapeHtmlAttr($item->getId()) ?>" 
                data-validate="{'required-number':true,'validate-greater-than-zero':true}"
                name="qty[<?= $block->escapeHtmlAttr($item->getId()) ?>]" 
                value="<?=/* @noEscape */  (int)($value) ?>"
                data-item-qty="<?= /* @noEscape */ (int)($value) ?>" 
                style="display: none;" />

                <input type="number" 
                data-role="qty" 
                id="qty-visible[<?= $block->escapeHtmlAttr($item->getId()) ?>]" 
                class="input-text qty qty-visible-<?= $block->escapeHtmlAttr($item->getId()) ?>" 
                data-validate="{'required-number':true,'validate-greater-than-zero':true}"
                name="qty[<?= $block->escapeHtmlAttr($item->getId()) ?>]" 
                value="<?=/* @noEscape */  (int)($value) ?>"
                data-item-qty="<?= /* @noEscape */ (int)($value) ?>" 
                disabled />
               <span class="plus">
                    <button
                            type="button" title="<?= __('Increase the quantity'); ?>"
                            class="plus-cart"
                            data-cart-item-id="<?php /* @escapeNotVerified */
                            echo $item->getId() ?>"
                            data-cart-item-increment="<?php echo $itemHelper->getQtyIncrementsByProduct($product); ?>"
                            data-role="plus-cart"
                    >+</button>
                </span>
            </div>
        </div>
    <?php endif; ?>
    <?php if ($product->isSaleable()): ?>
    <div class="product-item-actions">
        <div class="actions-primary">
            <button type="button" data-role="tocart" data-post='<?= /* @noEscape */ $block->getItemAddToCartParams($item) ?>' title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>" data-item-id="<?= $block->escapeHtmlAttr($item->getId()) ?>" class="action tocart primary">
                <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
            </button>
        </div>
    </div>
    <?php else: ?>
        <?php if ($product->getIsSalable()): ?>
            <p class="available stock" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                <span><?= $block->escapeHtml(__('In stock')) ?></span>
            </p>
        <?php else: ?>
            <p class="unavailable stock" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
            </p>
        <?php endif; ?>
    <?php endif; ?>
    </fieldset>
</div>
