<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
?>
<?php 
 $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
 $customerSession = $objectManager->get('Magento\Customer\Model\SessionFactory')->create();

 $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$config = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('alothemes/categorysearch', \Magento\Store\Model\ScopeInterface::SCOPE_STORE);
$catalogsearch = isset($config['enabled']) ? $config['enabled'] : 0;
?>
<link href="//fonts.googleapis.com/css?family=Libre+Baskerville:400,400i,700&display=swap" rel="stylesheet">
<link href="//fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap" rel="stylesheet">
<link href="//fonts.googleapis.com/css?family=Montserrat:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
<link href="//fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i&subset=latin-ext" rel="stylesheet">
<header class="page-header alothemes">
	<div class="header">	
		<div class="header-content menu-mobile header-sticker">
			<div class="container-fluid">
				<div class="row">					
				    <div class="content-logo">
						<div class="header-logo">
							<?php echo $this->getChildHtml('logo'); ?>
						</div>
					</div>				
					<div class="shopping-cart">
						<div class="nav-toggle-mobile">
							<div class="nav-toggle-main">
								<span data-action="toggle-nav" class="action nav-toggle">
									<span><?= /* @escapeNotVerified */ __('Toggle Nav') ?></span>
									<img class="loaded" src='<?php echo $this->getViewFileUrl('images/hamburger-black.svg'); ?>' alt="Show_menu">
								</span>
								<div class="tool-account alo-toggle tool-padding toggle-tab-mobile">
									<div class="<?php if($customerSession->isLoggedIn()) echo 'toggle-tab'; ?> outside-close mobile">
										<span class="fa fa-user icons account-icons <?php if(!$customerSession->isLoggedIn()) echo 'proceed-to-checkout' ?>"></span>										
									</div>
									<div class="toggle-content">
										<?php echo $this->getChildHtml('header.links'); ?>
									</div>
								</div>
							</div>
						</div>
						<div class="header-top-link">
							<?php echo $this->getChildHtml('store_language'); ?>
							<?php echo $this->getChildHtml('currency'); ?>
						</div>
						<div class="tool-header">
							<div class="search-area header-search">
								<?php echo $this->getChildHtml('top.search'); ?>
							</div>
							<div class="tool-account alo-toggle tool-padding toggle-tab-mobile">
								<div class="<?php if($customerSession->isLoggedIn()) echo 'toggle-tab'; ?> outside-close mobile">
									<span class="fa fa-user icons account-icons <?php if(!$customerSession->isLoggedIn()) echo 'proceed-to-checkout' ?>"></span>
								</div>
								<div class="toggle-content">
									<?php echo $this->getChildHtml('header.links'); ?>
								</div>
							</div>						
							<div class="header-top-link">
								<?php echo $this->getChildHtml('header.customlinks'); ?>
							</div>
							<?php echo $this->getChildHtml('minicart'); ?>
						</div>
					</div>				
					<div class="header-right-menu">
						<?php echo $this->getChildHtml('navigation.sections'); ?>
						<?php echo $this->getChildHtml('catalog.topnav'); ?>
					</div>				
					<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('social-profile')->toHtml();?>
				</div>
			</div>
		</div>
	</div>
</header>