<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile


?>
<div class="block newsletter block-subscribe">
        <form class="form subscribe clearfix"
            novalidate
            action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
			<div class="block-content">
				<div class="block-title">
					<span><?php echo __('subscribe our newsletter') ?></span>
				</div>
				<div class="field newsletter input-box clearfix">
				    <div class="subscribe-panel">
				    	<p class="panel-text"><?php echo __('Sign up for our newsletter to be updated on the latest designs, exclusive offers, inspiration and tips!') ?></p>
				    </div>
					<div class="visible">
						<div class="control">
							<input name="email" type="email" id="newsletter" class="input-text"
										placeholder="<?php /* @escapeNotVerified */ echo __('Your email') ?>"
										data-validate="{required:true, 'validate-email':true}"/>
						</div>
						<div class="actions">
							<button class="action subscribe button" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
								<span><?php /* @escapeNotVerified */ echo __('Sign up') ?></span>
							</button>
						</div>
					</div>
				</div>
			</div>
        </form>
</div>
